import pg from 'pg';
import dotenv from 'dotenv';
import fs from 'fs';

dotenv.config();

const { Pool } = pg;

const pool = new Pool({
    user: process.env.DB_USER,
    host: process.env.DB_HOST,
    database: process.env.DB_DATABASE,
    password: process.env.DB_PASSWORD,
    port: process.env.DB_PORT,
});

const tables = [
    'products',
    'customers',
    'suppliers',
    'supplier_products',
    'sales',
    'sale_items',
    'purchases',
    'purchase_items',
    'inventory_movements',
    'claims',
    'surveys'
];

const escapeLiteral = (str) => {
    if (str === null || str === undefined) return 'NULL';
    if (typeof str === 'number') return str;
    if (typeof str === 'boolean') return str ? 'TRUE' : 'FALSE';
    // Replace single quotes with two single quotes for SQL escaping
    return `'${String(str).replace(/'/g, "''")}'`;
};

const exportData = async () => {
    try {
        console.log("Starting database export...");
        let sqlContent = "-- Database Dump\n-- Generated by export_data.js\n\n";

        // Disable constraints temporarily if possible, or just order correctly.
        // Postgres doesn't have a simple "DISABLE FOREIGN KEYS" global command like MySQL.
        // We will use TRUNCATE CASCADE at the start.

        sqlContent += `BEGIN;\n\n`;
        sqlContent += `-- Clean existing data\n`;
        sqlContent += `TRUNCATE TABLE ${tables.join(', ')} RESTART IDENTITY CASCADE;\n\n`;

        for (const table of tables) {
            console.log(`Exporting ${table}...`);
            const res = await pool.query(`SELECT * FROM ${table}`);
            const rows = res.rows;

            if (rows.length > 0) {
                sqlContent += `-- Data for ${table}\n`;

                // Get columns
                const columns = Object.keys(rows[0]);

                for (const row of rows) {
                    const values = columns.map(col => escapeLiteral(row[col]));
                    sqlContent += `INSERT INTO ${table} (${columns.join(', ')}) VALUES (${values.join(', ')});\n`;
                }
                sqlContent += `\n`;
            }
        }

        sqlContent += `COMMIT;\n`;

        fs.writeFileSync('database_dump.sql', sqlContent);
        console.log("Export completed successfully. File saved as 'database_dump.sql'.");

    } catch (err) {
        console.error("Error exporting database:", err);
    } finally {
        await pool.end();
    }
};

exportData();
